### ISSUE TITLE
Dynamic table headers in table routing

### ISSUE THREAD

**Issue by alexzye** [CVBT-CalPoly/ecoan-web-app#1]
It would be beneficial if we were able to include dynamic table headers to be part of our tables routing functions. That is, in `routes/table/`, instead of having huge arrays like this:
``` javascript
var tableColumns = [
  "ProdNo",
  "ProdGrpCode",
  "ProdThaiName",
  "ProdEngName",
  "Picture",
  "ThaiModel",
  "EngModel",
  "MixNo",
  "ProdWt",
  "ColorMixNo",
  "FaceWt",
  "Mold",
  "PiecesPerMould",
  "ProductCost",
  "PriceRetail",
  "PriceWholeSale",
  "ProdStockGoal",
  "ThaiCom",
  "EngCom",
  "Status",
  "ChangeType",
  "ChangeDate",
  "ChangeTime"
];
```
that specify our table headers, we can have a simple function that takes the specific table and returns a list of strings. i.e.
``` javascript
var tableColumns = getTableHeaders("ProductHistory");
```
This would be beneficial for several reasons.
1. Reduce hard coding table data (duh)
2. Sequelize has an except query parameter that can query all __but__ any given columns.

We need this because sequelize makes too many assumptions about our dataset such as having a specified primary key. Since the dataset indexed through candidate and primary keys, we can't use the assumptions sequelize makes.

**Comment by alexzye** [comment]
What's the status of this, @jonnymolina ?

**Comment by jonnymolina** [comment]
#3 Done in this PR.

**Comment by alexzye** [comment]
Hey @jonnymolina , this implementation still stores static table headers. That is, we have to write the header names directly into code, outside of our models. Therefore, if any of the tables were to be modified, we would have to change the code to query as well as our models -- this is what we are trying to avoid. In other words, we are trying to remove lists like the one shown in the OP all together from our code. The way this function should work is that the code should _ask the database_ what the table's attributes are and return that. I would imagine you would have to use some <code>mySQL</code> or <code>Sequelize</code> calls to the database and ask what attributes are or get the data structures from our models.

**Comment by jonnymolina** [comment]
Oh I misunderstood this issue. That makes more sense. Typing all that stuff was a pain...

**Comment by jonnymolina** [comment]
New PR #6 for this issue.
