### ISSUE TITLE
Entire table loads instead of only loading the current visible rows

### ISSUE THREAD

**Issue by jonnymolina** [CVBT-CalPoly/ecoan-web-app#4]
When navigating to view tables, the entire table is loaded into the website. This is a performance issue since the client has to wait for the whole table to load before viewing it. Ideally, the client should only load a certain number of rows that they want to view at a time.

**Comment by alexzye** [comment]
Currently, I got the pages to load one by one via methods described in the [DataTable api for server side deferred loading](https://datatables.net/examples/server_side/defer_loading.html). However, now there is a bug in the page indexing.

Issue can be reproducible by simply loading any table page and advancing to a different page in the table.

**Comment by jonnymolina** [comment]
Merged to master on commit ac6e07c152282310a9d29c4cc720bde2297c21f7

Working for product history

**Comment by alexzye** [comment]
Closing this issue.
